### ISSUE TITLE
Dependencies not found

### ISSUE THREAD

**Issue by makerGeek** [thevpc/vr#15]
The latest version of vr uses libraries that are not (yet) published.
The aforementioned libraries include:

- [ ] dependency:  net.vpc.common.strings v.1.2.6    -- last found: v.1.2.3
- [ ] dependency:  net.vpc.common.utils v.1.6    -- last found: v.1.4
- [ ] dependency:  net.vpc.upa.api v.1.2.0.29   -- last found: v.1.2.0.28
- [ ] dependency:  net.vpc.upa.impl v.1.2.0.29.0   -- last found: v.1.2.0.29.0

**Comment by thevpc** [comment]
thanks, done.
