### ISSUE TITLE
Make Icons and Buttons more user-friendly

### ISSUE THREAD

**Issue by oussbenk** [thevpc/vr#25]
- [x] **Add texts to buttons** icons every time there is enough horizontal space

- [x] Add **title attribute** (or tooltips if possible) for each link

- [x]  Add some **shortcuts links in the main menu** such as:

   - acces to **`my folder`**
   - **`upload new file`**

**Comment by thevpc** [comment]
access to my folder : done

**Comment by oussbenk** [comment]
👍

**Comment by thevpc** [comment]
fixed 1.1.149. Need SHIFT F5 on browser to reload css.
