### ISSUE TITLE
Add custom welcome page

### ISSUE THREAD

**Issue by amal7** [thevpc/vr#36]
Add the possibility to customize welcome page url

**Comment by thevpc** [comment]
To Add a custom WelcomePage one must create a @VrController, implement WelcomeAlternative and mark the class with high priority (higher than 0)
Example : 

@VrController(
        breadcrumb = {@UPathItem(title = "Desktop", css = "fa-dashboard", ctrl = "")},
        title = "Dashboard",
        menu = "/Desktop",
        url = "modules/custom/dashboard",
        priority = 100
)
public class MyCustomDashboardCtrl implements  WelcomeAlternative {
}

If you want to have multiple dashboards based on profile you can consider implementing also VrActionEnabler as follows


@VrController(
        breadcrumb = {@UPathItem(title = "Desktop", css = "fa-dashboard", ctrl = "")},
        title = "Dashboard",
        menu = "/Desktop",
        url = "modules/custom/dashboard",
        priority = 100
)
public class MyCustomDashboardCtrl implements  WelcomeAlternative {
    @Override
    public boolean isEnabled(net.vpc.app.vainruling.core.web.VrActionInfo data) {
        return CorePlugin.get().hasProfile("GoodProfile");
    }
}
