### ISSUE TITLE
Log Out

### ISSUE THREAD

**Issue by houssembenhmida** [thevpc/vr#49]
when logging out, it shows an error instead of redirecting to the website

"HTTP Status 500 - getAttribute: Session already invalidated
type Exception report

message getAttribute: Session already invalidated

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.lang.IllegalStateException: getAttribute: Session already invalidated
	org.apache.catalina.session.StandardSession.getAttribute(StandardSession.java:1197)
	org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:108)
	net.vpc.app.vainruling.core.web.srv.session.HttpSessionAdapter.getAttribute(HttpSessionAdapter.java:73)
	net.bull.javamelody.MonitoringFilter.putUserInfoInSession(MonitoringFilter.java:310)
	net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:232)
	net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:178)
	net.vpc.app.vainruling.core.web.srv.TokenManagerFilter.doFilter(TokenManagerFilter.java:128)
	net.vpc.upa.web.UPAServletRequestFilter$1.run(UPAServletRequestFilter.java:83)
	net.vpc.upa.impl.config.VoidActionAdapter.run(VoidActionAdapter.java:24)
	net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:355)
	net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:292)
	net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:400)
	net.vpc.upa.web.UPAServletRequestFilter.doFilter(UPAServletRequestFilter.java:80)
note The full stack trace of the root cause is available in the Apache Tomcat/8.0.27 logs."

**Comment by thevpc** [comment]
fixed
